[general]
name = "tiledattention"
license = "Apache-2.0"
backends = [
  "cuda",
]
version = 1

[general.hub]
repo-id = "thisistaimur/tiledattention"

[torch]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h",
]

[kernel.tiledattention]
backend = "cuda"
depends = ["torch"]
src = ["tiledattention_cuda/tiledattention.cu"]
